services:
  caddy:
    image: caddy:latest # Should pin for stability
    restart: unless-stopped
    network_mode: host
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
      - "2019:2019"
    volumes:
      - ./conf:/etc/caddy
      - ./site:/srv
      - caddy_data:/data
      - caddy_config:/config
      - ./cloudflare:/cloudflare

volumes:
  caddy_data:
  caddy_config:
