services:
  caddy:
    image: caddy:2.9-alpine
    restart: unless-stopped
    network_mode: host
    container_name: caddy
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:2019/config/",
        ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      # - ./site:/srv
      - caddy_data:/data
      - caddy_config:/config
      - ./cloudflare:/cloudflare

volumes:
  caddy_data:
  caddy_config:
