services:
  headscale:
    image: headscale/headscale:0.26.1
    container_name: headscale
    restart: unless-stopped
    command: serve
    labels:
      me.tale.headplane.target: headscale
    networks:
      - headscale-internal
    ports:
      - "8080:8080"
    volumes:
      - headscale_data:/var/lib/headscale
      - ./headscale.yml:/etc/headscale/config.yaml:ro
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8080/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  headplane:
    image: ghcr.io/tale/headplane:0.6.0
    container_name: headplane
    restart: unless-stopped
    networks:
      - headscale-internal
    ports:
      - "3000:3000"
    volumes:
      - ./headplane.yml:/etc/headplane/config.yaml:ro
      - ./headscale.yml:/etc/headscale/config.yaml:ro
      - headplane_data:/var/lib/headplane
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      headscale:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000/",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  headscale-internal:
    driver: bridge

volumes:
  headscale_data:
    driver: local
  headplane_data:
    driver: local
