services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest # Should pin for stability
    container_name: homepage
    restart: unless-stopped
    ports:
      - "3005:3000"
    volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - TZ=America/Chicago
      - HOMEPAGE_ALLOWED_HOSTS=jobot-services.com,homepage.jobot-services.com,localhost:3005
