services:
  arcane-agent:
    image: ghcr.io/ofkm/arcane-headless:latest
    container_name: arcane-agent
    ports:
      - "3553:3553"
    environment:
      - AGENT_MODE=true
      # Use a strong, temporary bootstrap token for pairing:
      - AGENT_BOOTSTRAP_TOKEN=TOKEN
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - agent-data:/app/data
      - /home/jobot2397/containers:/data/projects:rw
    restart: unless-stopped

volumes:
  agent-data: {}
