services:
  arcane:
    image: ghcr.io/ofkm/arcane:latest
    container_name: arcane
    restart: unless-stopped
    ports:
      - 3552:3552
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - arcane-data:/app/data
      - /home/jobot2397/containers:/compose-files:rw
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3552/",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - arcane-network
    labels:
      - homepage.group=Hopper
      - homepage.name=Arcane
      - homepage.icon=sh-arcane.svg
      - homepage.href=https://arcane.jobot-services.com/
      - homepage.description=Docker server management

  postgres:
    image: postgres:17-alpine
    container_name: arcane-postgres
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - arcane-network
networks:
  arcane-network:
    driver: bridge
volumes:
  arcane-data:
    driver: local
  postgres-data:
    driver: local
