services:
  arcane:
    image: ghcr.io/ofkm/arcane:latest
    container_name: arcane
    ports:
      - "3552:3552"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - arcane-data:/app/data
      - ../:/app/data/projects
    env_file:
      - .env
    environment:
      - APP_URL=http://localhost:3552
      - PUID=1000
      - PGID=1000
    restart: unless-stopped

volumes:
  arcane-data:
