services:
  beszel-agent:
    image: henrygd/beszel-agent
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - beszel_agent_data:/var/lib/beszel-agent
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # monitor other disks / partitions by mounting a folder in /extra-filesystems
      # - /mnt/disk1/.beszel:/extra-filesystems/disk1:ro
    env_file:
      - .env
    environment:
      PORT: 45876
      HUB_URL: "https://beszel.jobot-services.com"
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 45876 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

volumes:
  beszel_agent_data:
    driver: local
